#! /bin/sh

local_port=$1
ssh_server=vision
url_tmpl=http://www\\1.domain.tld/

exec 3>&1
eval ssh -N -T $ssh_server -R 0:localhost:$local_port 2>&1 1>&3 \
    | sed 's|^Allocated port \([[:digit:]]\+\) for remote forward to|Your url is '$url_tmpl' will be forwarded to|'
