theme="solarized_dark"

[editor]
bufferline = "multiple"
auto-save = true
auto-format = true
line-number = "relative"

[editor.cursor-shape]
insert="bar"

[editor.file-picker]
hidden = false

[keys.normal.space]
w = ":w"
q = ":bc"
e = ":q"

[keys.normal]
# move line down
"A-down" = ["extend_line","delete_selection", "paste_after","goto_line_start"]
# move line up
"A-up" = ["extend_line","delete_selection","move_line_up","paste_before","goto_line_start"]
# use esc to deselct / remove mutliple cursors
esc = ["collapse_selection","keep_primary_selection"]
